# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-json
          # - id: check-shebang-scripts-are-executable
          # - id: pretty-format-json
          # - id: check-merge-conflict
          - id: check-toml
          - id: detect-aws-credentials
          - id: detect-private-key
          - id: fix-byte-order-marker
          - id: mixed-line-ending
    ##### DOCKER #####
    - repo: https://github.com/AleksaC/hadolint-py
      rev: v1.19.0
      hooks:
          - id: hadolint
            args: [--ignore, DL3025, --ignore, DL3018, --ignore DL3033]
