repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-toml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/kahnwong/pre-commit
    rev: "24f2010"
    hooks:
      - id: hadolint
