version: '3.3'
services:
  fava:
    build: .
    container_name: fava
    environment:
      BEANCOUNT_FILE: /input.beancount
      TZ: Asia/Bangkok
    ports:
      - '5004:5000' # on mac, port 5000 is used by airplay
    volumes:
      - /Users/kahnwong/Cloud/Apps/fava/:/opt/fava/
    restart: unless-stopped
